<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC2017000016" ignored="0" name="PledgeeInitiation-PledgeeRedeem" tests="2" failures="1" timestamp="16 Jan 2018 10:07:27 GMT" time="206.33" errors="0">
  <testcase name="Pledgee_Initiation_Submit" time="157.449" classname="NERL.Pledgee_Initiation_Main"/>
  <testcase name="Pledgee_creation1" time="30.669" classname="withdrawal_pkg.PledgeeRedemption_main">
    <failure type="java.lang.AssertionError" message="expected [Pledge Redeem submitted Successfully] but found [Saved Successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Pledge Redeem submitted Successfully] but found [Saved Successfully.]
	at withdrawal_pkg.PledgeeRedemption_main.Pledgee_creation1(PledgeeRedemption_main.java:152)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Pledgee_creation1 -->
</testsuite> <!-- PledgeeInitiation-PledgeeRedeem -->
